### ISSUE TITLE
General statement to get rid of tests at the end of your finished code

### ISSUE THREAD

**Issue by RileyPaddock** [eoriont/machine-learning#13]
You have a lot of tests at the end of code. I know you put it in the if __name__ == __main__ but I cannot find anything else in your code to make an issue about.

**Comment by eoriont** [comment]
Fixed. I have a habit of putting code at the end of my class files, because for my IDE, it's easiest to run the file I currently have open. As you imply, it isn't great to just have a bunch of tests lying around, but I generally use them for the couple assignments while we work on the class in question.
