### ISSUE TITLE
Many issues in 1

### ISSUE THREAD

**Issue by C0BBL3** [eoriont/machine-learning#7]
(For data frame)
1. There is no need for your from_mat function you can just write your from_array function as so: ` return DataFrame({col: list(arr) for col, arr in zip(cols, zip(*mat))}, cols)`
2. You could shorten your select_rows by just looping through the indices and getting the row by index.
3. You could shorten your select_rows_where by doing a similar thing as select_rows by just looping over the rows and getting the indices and using select_rows as the rest of the code for select_rows_where.
4. your order by function is a waaaaay too complex, you can just use a quick sort method using the built-in `min` function to sort the list and make the quick sort return the indices and use select_rows to finish off the function. (I was able to do this (excluding the quicksort function) in 2 lines, 1 if I wanted to but Justin will get mad at me).
5. What is trim_column its not referenced anywhere in your code?

**Comment by eoriont** [comment]
1. Fixed in 5473cd7

**Comment by eoriont** [comment]
2. Added
3. Thanks for the suggestion, I ended up using `DataFrame.from_array()` and `to_array()` to go through the entries manually. I don't use the other function for this because the lambda function takes in the whole row, not the index.
4. I made it simpler, and since you like (almost) one liners (there it is)
5. That was actually just for the college application thing where I had to replace 0's and 1's with 0.2's and 0.8's. I put that in the actual file I needed it in so it isn't confusing.
