### ISSUE TITLE
Static, class method from array

### ISSUE THREAD

**Issue by geomeza** [eoriont/machine-learning#8]
There is literally no reason for you to make a static method and call it from your class method, you can just do the same singular line inside the class method

**Comment by eoriont** [comment]
That's 100% true.

The reason I even had a `from_mat` function in the first place was because we had this one assignment (before we created `from_array`) which required that functionality. At the time, I didn't know that `@classmethod`s existed, so I just used a `@staticmethod` to the same effect. When implementing the new `from_array` function, I just called my old function, since they both had the exact same functionality. I kept the old one for backwards-compatibility's sake, but that's just me being lazy.

Fixed in 5473cd7
