### ISSUE TITLE
Lots of single letter variables

### ISSUE THREAD

**Issue by RileyPaddock** [eoriont/machine-learning#9]
In your kNearestNeighborsClassifier you use a lot of variables that are just a single letter but are not indicies. Like m for max and c for columns. Your code would be easier to read if you just put what they were instead of just the letter.

**Comment by eoriont** [comment]
Fixed in aef4e2a. The reason why I use single letter variables is because my linter usually lets me put them in one liners, but it definitely obfuscates my code to a degree. I changed the ones that you mentioned, but I didn't really see anything else that was impossible to read. (I think I did an okay job in KNN)
